# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
